"""empty message

Revision ID: 592dfb7afe41
Revises: 28d82d40c83b
Create Date: 2015-10-29 17:52:46.179000

"""

# revision identifiers, used by Alembic.
revision = '592dfb7afe41'
down_revision = '28d82d40c83b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_modified')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
